name: Industrialisation continue sur le serveur AWS
on: push
jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: |
          jar cvf MSPRjessica.war *
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DNS }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.MY_PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "MSPRjessica.war"
        target: "/opt/tomcat/webapps"
